### ISSUE TITLE
Uso de Alt + tab

### ISSUE THREAD

**Issue by Walter-Lz** [Leiner117/Mini-Python#2]
@Stevennnncz hace falta la funcionalidad de  shift + tab.

**Comment by Stevennnncz** [comment]
[like]  STEVEN FERNANDO CHACON ZARATE reacted to your message:
________________________________
From: Walter Lazo ***@***.***>
Sent: Monday, September 9, 2024 10:23:20 PM
To: Leiner117/Mini-Python ***@***.***>
Cc: STEVEN FERNANDO CHACON ZARATE ***@***.***>; Mention ***@***.***>
Subject: [Leiner117/Mini-Python] Uso de Alt + tab (Issue #2)

@ Stevennnncz hace falta la funcionalidad de alt + tab. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <Leiner117/Mini-Python/issues/2@ github. com>
ZjQcmQRYFpfptBannerStart
Este mensaje proviene de un remitente externo
Este mensaje vino de fuera de su organización.

ZjQcmQRYFpfptBannerEnd

@Stevennnncz<https://urldefense.com/v3/__https://github.com/Stevennnncz__;!!O7R4XxaP!bq8jkkPMsfKaAOyELOl2-llql0lxq5Zrbi3J6G0LApXO7eAmkR-4EzYdEblYTgECElltaA_CpsLtjC_Ba9I6PTKyY2ub3w$> hace falta la funcionalidad de alt + tab.

**Comment by Stevennnncz** [comment]
Se corrige el shit+tab, alt+tab pendiente
